name: Benchmark

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run Criterion Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: cargo bench
        run: cargo bench -p quince-qfl -- --output-format bencher | tee output.txt

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: QFL Criterion Benchmarks
          tool: cargo
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: false
